### ISSUE TITLE
addon not working in jarvis 16.1 please make this addon compatible

### ISSUE THREAD

**Issue by daniel-ntl** [kodibear/plugin.video.watchcartoononline#2]
hi, kodibear, i installed your addon, and i cannot open all the menu there (like dub..sub..movie.. etc), i realized that my kodi is jarvis 16.1, but i cannot change this because my tv box is android 4.2.2, so please make this addon compatible to jarvis 16.1,? (the old WCO can go to the movie list but cannot play)
thx again
daniel

**Comment by kodibear** [comment]
It should be working on Jarvis, I'll see if it's not something broken in general. Thanks for the support!

**Comment by kodibear** [comment]
I've released a new version, which should fix the problem, even for Jarvis 16.1. Can you try it out and close the issue if this resolves the problem for you?

**Comment by daniel-ntl** [comment]
soon i'll try your new update, just wait a moment

________________________________

**Comment by daniel-ntl** [comment]
wow, thanks man, your WCO does work in jarvis 16.1 even in frodo are working, man this is good
