### ISSUE TITLE
Doesn't work anymore needs fix

### ISSUE THREAD

**Issue by sdstreams** [kodibear/plugin.video.watchcartoononline#3]
Hello Kodibear and thank you for your work trying to keep this very amazing addon alive. Ive notice today that any section I click on I get an "error check log". Would this be something you would fix or is it going to be done as of now.

Thank You

**Comment by kodibear** [comment]
I'll look into it

**Comment by kodibear** [comment]
I've released a new version, and the fix works for me. Can you try it out and close the issue if this resolves the problem for you?
